project_id = "uvczawicaqqiyutcqoyg"

[functions.wake-up-backend]
verify_jwt = false

[functions.submit-message]
verify_jwt = false

[functions.admin-users]
verify_jwt = true

[functions.admin-users-with-emails]
verify_jwt = true

[functions.create-payment-token]
verify_jwt = true

[functions.export-csv]
verify_jwt = true

[functions.sync-products]
verify_jwt = true

[functions.promote-user-admin]
verify_jwt = true

[functions.send-contact-email]
verify_jwt = true

[functions.send-secure-webhook]
verify_jwt = true

[functions.send-support-email]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.delete-account]
verify_jwt = true
