// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mivzoeormbjzspbglebh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1pdnpvZW9ybWJqenNwYmdsZWJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NzUxNDcsImV4cCI6MjA3MTI1MTE0N30.P8FsJS7tppzYl_tSm2FZhhXD8iV8kuXsJDqN56l6MTs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});