// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvczawicaqqiyutcqoyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2Y3phd2ljYXFxaXl1dGNxb3lnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNjczNDAsImV4cCI6MjA2ODY0MzM0MH0.m3NCcH46Dfce34aVgEYbF08Bh_6rkMIDB6UF6z6xLLY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    debug: true // 🔍 Enable debug mode to catch refresh errors
  }
});

// 🔍 DIAGNOSTIC: Global error handler for auth failures
supabase.auth.onAuthStateChange((event, session) => {
  if (event === 'SIGNED_OUT' && !session) {
    console.log("🚨 CRITICAL: Unexpected SIGNED_OUT event detected");
    console.log("📍 Location:", window.location.href);
    console.log("🕐 Timestamp:", new Date().toISOString());
    
    // Check localStorage for any remaining auth data
    const authKeys = Object.keys(localStorage).filter(key => key.includes('auth') || key.includes('supabase'));
    console.log("🔑 Auth keys in localStorage:", authKeys);
  }
});